labels:
  env: dev
spec:
  destination:
    server: https://kubernetes.default.svc
  source:
    repoURL: https://github.com/tamer84/saas-workloads.git
    targetRevision: main

  # Thoses default values can be surcharged by Infrastructure as Code
  env: dev
  clusterName: saas-cluster-dev # the name of EKS cluster

  ingress:
    type: 'alb' # nginx | alb
    host: 'dev.tamer84.com' # empty or your domain like dev.example.com
